### ISSUE TITLE
Not loading icons

### ISSUE THREAD

**Issue by SturmB** [Torben2000/keypirinha-goggalaxy#6]
I'm getting an error when first installing this package:

```
00:25:48.201 Plugin loaded: goggalaxy.goggalaxy (instance #1)
00:25:50.137 WARNING: goggalaxy.goggalaxy: dwebp.exe not found, icons will not be loaded
00:25:50.211 goggalaxy.goggalaxy: Cataloged 1317 games (incl. 152 installed) in 2.0 seconds
```

**Comment by Torben2000** [comment]
Loading icons is optional as it requires some conversion from the image format GOG Galaxy uses. See [optional part of installation in README](https://github.com/Torben2000/keypirinha-goggalaxy#optional) for correct integration of dwebp.exe which will do the conversion.

As a small warning: It will take some time (probably some minutes) before conversion is done because of your library size (mine is similar so I know what I'm talking about 😉). During that time Keypirinha might be unresponsive. This is only required once, the converted images will be cached.

**Comment by SturmB** [comment]
Yep, that takes care of it. My apologies for not reading the documentation more thoroughly.

You may want to consider adding a short note to the doc warning users about Keypirinha's unresponsiveness while it builds a cache of icons for large libraries.

**Comment by Torben2000** [comment]
Good idea, I added the info to the description.

Thanks for your feedback!
