### ISSUE TITLE
in keypirinha naming question

### ISSUE THREAD

**Issue by itmestan** [Torben2000/keypirinha-goggalaxy#8]
hi! love the functionality of the plugin, thank you so much for putting it together. 

one quick question. I'm wondering if there's a way we can chose to or opt out of the "AMG" naming scheme? 

when searching for a game, I see "AMG Steam: Hades". seeing the AMG and platform ahead of the game breaks much of the continuity of keypirinha and can throw me off. while this is a nitpicky preference, is there a chance we can have this as an option in the configuration to simply opt out of "AMD [Platform]" when searching?

let me know please, thx!

**Comment by Torben2000** [comment]
Hi,

you are most likely using this plugin: https://github.com/TanninOne/keypirinha-allmygames

The stuff that you reported does not match anything that my plugin does, but matches the other one. So you should report an issue over there. 😄 

...but thanks anyway, because this bug report made me look at the plugin again. So I could figure out that it was broken for some time and needed a fix (which will be arriving in a few minutes).

**Comment by itmestan** [comment]
my bad, thx for the correction! will re-post over there.
